//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WageManagementSystem.GetEmployeeInfoBySchool {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DominoSoapBinding", Namespace="urn:DefaultNamespace")]
    public partial class EmployeeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SYNEMPLOYEEOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EmployeeService() {
            this.Url = global::WageManagementSystem.Properties.Settings.Default.WageManagementSystem_GetEmployeeInfoBySchool_EmployeeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SYNEMPLOYEECompletedEventHandler SYNEMPLOYEECompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:DefaultNamespace", ResponseNamespace="urn:DefaultNamespace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SYNEMPLOYEEReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SVCBODYS SYNEMPLOYEE([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] SVCHDR OSVCHDR, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] APPHDR OAPPHDR, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] APPBODY OAPPBODY) {
            object[] results = this.Invoke("SYNEMPLOYEE", new object[] {
                        OSVCHDR,
                        OAPPHDR,
                        OAPPBODY});
            return ((SVCBODYS)(results[0]));
        }
        
        /// <remarks/>
        public void SYNEMPLOYEEAsync(SVCHDR OSVCHDR, APPHDR OAPPHDR, APPBODY OAPPBODY) {
            this.SYNEMPLOYEEAsync(OSVCHDR, OAPPHDR, OAPPBODY, null);
        }
        
        /// <remarks/>
        public void SYNEMPLOYEEAsync(SVCHDR OSVCHDR, APPHDR OAPPHDR, APPBODY OAPPBODY, object userState) {
            if ((this.SYNEMPLOYEEOperationCompleted == null)) {
                this.SYNEMPLOYEEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSYNEMPLOYEEOperationCompleted);
            }
            this.InvokeAsync("SYNEMPLOYEE", new object[] {
                        OSVCHDR,
                        OAPPHDR,
                        OAPPBODY}, this.SYNEMPLOYEEOperationCompleted, userState);
        }
        
        private void OnSYNEMPLOYEEOperationCompleted(object arg) {
            if ((this.SYNEMPLOYEECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SYNEMPLOYEECompleted(this, new SYNEMPLOYEECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class SVCHDR {
        
        private string sOURCEIDField;
        
        private string dESTINATIONIDField;
        
        private string tYPEField;
        
        private string iPADDRESSField;
        
        private string boField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOURCEID {
            get {
                return this.sOURCEIDField;
            }
            set {
                this.sOURCEIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESTINATIONID {
            get {
                return this.dESTINATIONIDField;
            }
            set {
                this.dESTINATIONIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IPADDRESS {
            get {
                return this.iPADDRESSField;
            }
            set {
                this.iPADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BO {
            get {
                return this.boField;
            }
            set {
                this.boField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class EMPLOYEEINFO {
        
        private string eMPLOYEEIDField;
        
        private string eMPLOYEENAMEField;
        
        private string gENDERField;
        
        private string cOMPOSITIONField;
        
        private string cOMRANKField;
        
        private string eNROLLMENTDATEField;
        
        private string rESIGNATIONDATEField;
        
        private string dEADLINEField;
        
        private string sCHOOLNAMEField;
        
        private string dEPARTMENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMPLOYEEID {
            get {
                return this.eMPLOYEEIDField;
            }
            set {
                this.eMPLOYEEIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMPLOYEENAME {
            get {
                return this.eMPLOYEENAMEField;
            }
            set {
                this.eMPLOYEENAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GENDER {
            get {
                return this.gENDERField;
            }
            set {
                this.gENDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMPOSITION {
            get {
                return this.cOMPOSITIONField;
            }
            set {
                this.cOMPOSITIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMRANK {
            get {
                return this.cOMRANKField;
            }
            set {
                this.cOMRANKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENROLLMENTDATE {
            get {
                return this.eNROLLMENTDATEField;
            }
            set {
                this.eNROLLMENTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESIGNATIONDATE {
            get {
                return this.rESIGNATIONDATEField;
            }
            set {
                this.rESIGNATIONDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEADLINE {
            get {
                return this.dEADLINEField;
            }
            set {
                this.dEADLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SCHOOLNAME {
            get {
                return this.sCHOOLNAMEField;
            }
            set {
                this.sCHOOLNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEPARTMENT {
            get {
                return this.dEPARTMENTField;
            }
            set {
                this.dEPARTMENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class APPBODYS {
        
        private EMPLOYEEINFO[] eMPLOYEESField;
        
        private string uSER01Field;
        
        private string uSER02Field;
        
        private string uSER03Field;
        
        private string uSER04Field;
        
        private string uSER05Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EMPLOYEES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public EMPLOYEEINFO[] EMPLOYEES {
            get {
                return this.eMPLOYEESField;
            }
            set {
                this.eMPLOYEESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER01 {
            get {
                return this.uSER01Field;
            }
            set {
                this.uSER01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER02 {
            get {
                return this.uSER02Field;
            }
            set {
                this.uSER02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER03 {
            get {
                return this.uSER03Field;
            }
            set {
                this.uSER03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER04 {
            get {
                return this.uSER04Field;
            }
            set {
                this.uSER04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER05 {
            get {
                return this.uSER05Field;
            }
            set {
                this.uSER05Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class APPHDRS {
        
        private string uSER01Field;
        
        private string uSER02Field;
        
        private string uSER03Field;
        
        private string uSER04Field;
        
        private string uSER05Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER01 {
            get {
                return this.uSER01Field;
            }
            set {
                this.uSER01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER02 {
            get {
                return this.uSER02Field;
            }
            set {
                this.uSER02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER03 {
            get {
                return this.uSER03Field;
            }
            set {
                this.uSER03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER04 {
            get {
                return this.uSER04Field;
            }
            set {
                this.uSER04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER05 {
            get {
                return this.uSER05Field;
            }
            set {
                this.uSER05Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class SVCHDRS {
        
        private string rCODEField;
        
        private string rDESCField;
        
        private string eSBCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RCODE {
            get {
                return this.rCODEField;
            }
            set {
                this.rCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RDESC {
            get {
                return this.rDESCField;
            }
            set {
                this.rDESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ESBCODE {
            get {
                return this.eSBCODEField;
            }
            set {
                this.eSBCODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class SVCBODYS {
        
        private SVCHDRS oSVCHDRSField;
        
        private APPHDRS oAPPHDRSField;
        
        private APPBODYS oAPPBODYSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SVCHDRS OSVCHDRS {
            get {
                return this.oSVCHDRSField;
            }
            set {
                this.oSVCHDRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public APPHDRS OAPPHDRS {
            get {
                return this.oAPPHDRSField;
            }
            set {
                this.oAPPHDRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public APPBODYS OAPPBODYS {
            get {
                return this.oAPPBODYSField;
            }
            set {
                this.oAPPBODYSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class HR_EMPLOYEE_ITEM {
        
        private string eR_IDField;
        
        private string eR_CODEField;
        
        private string eMPLOYEE_CODEField;
        
        private string iD_NUMBERField;
        
        private string sIGN_ORGField;
        
        private string sIGN_DATEField;
        
        private string eXPIRED_DATEField;
        
        private string cARD_NUMBERField;
        
        private string eMPLOYEE_NAMEField;
        
        private string mNEMONIC_CODEField;
        
        private string eNGLISH_NAMEField;
        
        private string aVATAR_ID1Field;
        
        private string aVATAR_ID2Field;
        
        private string bIRTHDAYField;
        
        private string sEXField;
        
        private string bWDAYField;
        
        private string bWYEARField;
        
        private string hIREDDAYField;
        
        private string lJDATEField;
        
        private string dEGREEField;
        
        private string mARRIEDField;
        
        private string nATIONALITYField;
        
        private string nATIVEIDField;
        
        private string nATIVEPLACEField;
        
        private string aDDRESSField;
        
        private string nATIONField;
        
        private string eMAILField;
        
        private string eMPSTATIDField;
        
        private string mODIFYField;
        
        private string uSEDNAMEField;
        
        private string pLDCPField;
        
        private string mAJORField;
        
        private string rEGISTERTYPEField;
        
        private string rEGISTERADDRESSField;
        
        private string hEALTHField;
        
        private string mEDICALHISTORYField;
        
        private string bLOODTYPEField;
        
        private string hEIGHTField;
        
        private string iMPORTWAYField;
        
        private string iMPORTORField;
        
        private string cELLPHONEField;
        
        private string uRGENCYCONTACTField;
        
        private string uRMAILField;
        
        private string tELPHONEField;
        
        private string iNTRODUCERField;
        
        private string gUARANTORField;
        
        private string sKILLField;
        
        private string sKILLFULLANGUAGEField;
        
        private string sPECIALITYField;
        
        private string wELFAREField;
        
        private string tALENTSTYPEField;
        
        private string eMNATUREField;
        
        private string oRGIDField;
        
        private string oRGCODEField;
        
        private string oRGNAMEField;
        
        private string uORGIDField;
        
        private string uORGCODEField;
        
        private string uORGNAMEField;
        
        private string uIDPATHField;
        
        private string hWC_NAMEZLField;
        
        private string lV_IDField;
        
        private string lV_NUMField;
        
        private string hG_IDField;
        
        private string hG_CODEField;
        
        private string hG_NAMEField;
        
        private string oSPIDField;
        
        private string oSPCODEField;
        
        private string sP_NAMEField;
        
        private string iSKEYField;
        
        private string hWC_NAMEZQField;
        
        private string hWC_NAMEZZField;
        
        private string uSABLEField;
        
        private string sSCURTY_ADDRField;
        
        private string sSCURTY_STARTDATEField;
        
        private string sSCURTY_ENDDATEField;
        
        private string sHOESIZEField;
        
        private string pANTS_CODEField;
        
        private string cOAT_CODEField;
        
        private string nEEDDROMField;
        
        private string dORM_BEDField;
        
        private string pAY_WAYField;
        
        private string sCHEDTYPEField;
        
        private string aTDTYPEField;
        
        private string rESIGNTIMESField;
        
        private string wFBUSYSSField;
        
        private string nOCLOCKField;
        
        private string pROMOTIONDAYField;
        
        private string eNTRYSOURCRField;
        
        private string rECTCODEField;
        
        private string rECTNAMEField;
        
        private string nOTEField;
        
        private string aTTIDField;
        
        private string eNTIDField;
        
        private string iDPATHField;
        
        private string cREATORField;
        
        private string cREATETIMEField;
        
        private string uPDATORField;
        
        private string uPDATETIMEField;
        
        private string pROPERTY1Field;
        
        private string pROPERTY2Field;
        
        private string pROPERTY3Field;
        
        private string pROPERTY4Field;
        
        private string pROPERTY5Field;
        
        private string iNSURANCESTATField;
        
        private string aDVISERCODEField;
        
        private string aDVISERNAMEField;
        
        private string aDVISERPHONEField;
        
        private string jURIDICALField;
        
        private string tRANSORGField;
        
        private string tRANSEXTIMEField;
        
        private string dISPUNITField;
        
        private string dISPEEXTIMEField;
        
        private string kQDATE_STARTField;
        
        private string kQDATE_ENDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ER_ID {
            get {
                return this.eR_IDField;
            }
            set {
                this.eR_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ER_CODE {
            get {
                return this.eR_CODEField;
            }
            set {
                this.eR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMPLOYEE_CODE {
            get {
                return this.eMPLOYEE_CODEField;
            }
            set {
                this.eMPLOYEE_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID_NUMBER {
            get {
                return this.iD_NUMBERField;
            }
            set {
                this.iD_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGN_ORG {
            get {
                return this.sIGN_ORGField;
            }
            set {
                this.sIGN_ORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGN_DATE {
            get {
                return this.sIGN_DATEField;
            }
            set {
                this.sIGN_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXPIRED_DATE {
            get {
                return this.eXPIRED_DATEField;
            }
            set {
                this.eXPIRED_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CARD_NUMBER {
            get {
                return this.cARD_NUMBERField;
            }
            set {
                this.cARD_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMPLOYEE_NAME {
            get {
                return this.eMPLOYEE_NAMEField;
            }
            set {
                this.eMPLOYEE_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MNEMONIC_CODE {
            get {
                return this.mNEMONIC_CODEField;
            }
            set {
                this.mNEMONIC_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENGLISH_NAME {
            get {
                return this.eNGLISH_NAMEField;
            }
            set {
                this.eNGLISH_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AVATAR_ID1 {
            get {
                return this.aVATAR_ID1Field;
            }
            set {
                this.aVATAR_ID1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AVATAR_ID2 {
            get {
                return this.aVATAR_ID2Field;
            }
            set {
                this.aVATAR_ID2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIRTHDAY {
            get {
                return this.bIRTHDAYField;
            }
            set {
                this.bIRTHDAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEX {
            get {
                return this.sEXField;
            }
            set {
                this.sEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BWDAY {
            get {
                return this.bWDAYField;
            }
            set {
                this.bWDAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BWYEAR {
            get {
                return this.bWYEARField;
            }
            set {
                this.bWYEARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HIREDDAY {
            get {
                return this.hIREDDAYField;
            }
            set {
                this.hIREDDAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LJDATE {
            get {
                return this.lJDATEField;
            }
            set {
                this.lJDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEGREE {
            get {
                return this.dEGREEField;
            }
            set {
                this.dEGREEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MARRIED {
            get {
                return this.mARRIEDField;
            }
            set {
                this.mARRIEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NATIONALITY {
            get {
                return this.nATIONALITYField;
            }
            set {
                this.nATIONALITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NATIVEID {
            get {
                return this.nATIVEIDField;
            }
            set {
                this.nATIVEIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NATIVEPLACE {
            get {
                return this.nATIVEPLACEField;
            }
            set {
                this.nATIVEPLACEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRESS {
            get {
                return this.aDDRESSField;
            }
            set {
                this.aDDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NATION {
            get {
                return this.nATIONField;
            }
            set {
                this.nATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMPSTATID {
            get {
                return this.eMPSTATIDField;
            }
            set {
                this.eMPSTATIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MODIFY {
            get {
                return this.mODIFYField;
            }
            set {
                this.mODIFYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USEDNAME {
            get {
                return this.uSEDNAMEField;
            }
            set {
                this.uSEDNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PLDCP {
            get {
                return this.pLDCPField;
            }
            set {
                this.pLDCPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAJOR {
            get {
                return this.mAJORField;
            }
            set {
                this.mAJORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REGISTERTYPE {
            get {
                return this.rEGISTERTYPEField;
            }
            set {
                this.rEGISTERTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REGISTERADDRESS {
            get {
                return this.rEGISTERADDRESSField;
            }
            set {
                this.rEGISTERADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HEALTH {
            get {
                return this.hEALTHField;
            }
            set {
                this.hEALTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEDICALHISTORY {
            get {
                return this.mEDICALHISTORYField;
            }
            set {
                this.mEDICALHISTORYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BLOODTYPE {
            get {
                return this.bLOODTYPEField;
            }
            set {
                this.bLOODTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HEIGHT {
            get {
                return this.hEIGHTField;
            }
            set {
                this.hEIGHTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IMPORTWAY {
            get {
                return this.iMPORTWAYField;
            }
            set {
                this.iMPORTWAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IMPORTOR {
            get {
                return this.iMPORTORField;
            }
            set {
                this.iMPORTORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CELLPHONE {
            get {
                return this.cELLPHONEField;
            }
            set {
                this.cELLPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URGENCYCONTACT {
            get {
                return this.uRGENCYCONTACTField;
            }
            set {
                this.uRGENCYCONTACTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URMAIL {
            get {
                return this.uRMAILField;
            }
            set {
                this.uRMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TELPHONE {
            get {
                return this.tELPHONEField;
            }
            set {
                this.tELPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTRODUCER {
            get {
                return this.iNTRODUCERField;
            }
            set {
                this.iNTRODUCERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GUARANTOR {
            get {
                return this.gUARANTORField;
            }
            set {
                this.gUARANTORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SKILL {
            get {
                return this.sKILLField;
            }
            set {
                this.sKILLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SKILLFULLANGUAGE {
            get {
                return this.sKILLFULLANGUAGEField;
            }
            set {
                this.sKILLFULLANGUAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SPECIALITY {
            get {
                return this.sPECIALITYField;
            }
            set {
                this.sPECIALITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WELFARE {
            get {
                return this.wELFAREField;
            }
            set {
                this.wELFAREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TALENTSTYPE {
            get {
                return this.tALENTSTYPEField;
            }
            set {
                this.tALENTSTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMNATURE {
            get {
                return this.eMNATUREField;
            }
            set {
                this.eMNATUREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORGID {
            get {
                return this.oRGIDField;
            }
            set {
                this.oRGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORGCODE {
            get {
                return this.oRGCODEField;
            }
            set {
                this.oRGCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORGNAME {
            get {
                return this.oRGNAMEField;
            }
            set {
                this.oRGNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UORGID {
            get {
                return this.uORGIDField;
            }
            set {
                this.uORGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UORGCODE {
            get {
                return this.uORGCODEField;
            }
            set {
                this.uORGCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UORGNAME {
            get {
                return this.uORGNAMEField;
            }
            set {
                this.uORGNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UIDPATH {
            get {
                return this.uIDPATHField;
            }
            set {
                this.uIDPATHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HWC_NAMEZL {
            get {
                return this.hWC_NAMEZLField;
            }
            set {
                this.hWC_NAMEZLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LV_ID {
            get {
                return this.lV_IDField;
            }
            set {
                this.lV_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LV_NUM {
            get {
                return this.lV_NUMField;
            }
            set {
                this.lV_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HG_ID {
            get {
                return this.hG_IDField;
            }
            set {
                this.hG_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HG_CODE {
            get {
                return this.hG_CODEField;
            }
            set {
                this.hG_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HG_NAME {
            get {
                return this.hG_NAMEField;
            }
            set {
                this.hG_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OSPID {
            get {
                return this.oSPIDField;
            }
            set {
                this.oSPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OSPCODE {
            get {
                return this.oSPCODEField;
            }
            set {
                this.oSPCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SP_NAME {
            get {
                return this.sP_NAMEField;
            }
            set {
                this.sP_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISKEY {
            get {
                return this.iSKEYField;
            }
            set {
                this.iSKEYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HWC_NAMEZQ {
            get {
                return this.hWC_NAMEZQField;
            }
            set {
                this.hWC_NAMEZQField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HWC_NAMEZZ {
            get {
                return this.hWC_NAMEZZField;
            }
            set {
                this.hWC_NAMEZZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USABLE {
            get {
                return this.uSABLEField;
            }
            set {
                this.uSABLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SSCURTY_ADDR {
            get {
                return this.sSCURTY_ADDRField;
            }
            set {
                this.sSCURTY_ADDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SSCURTY_STARTDATE {
            get {
                return this.sSCURTY_STARTDATEField;
            }
            set {
                this.sSCURTY_STARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SSCURTY_ENDDATE {
            get {
                return this.sSCURTY_ENDDATEField;
            }
            set {
                this.sSCURTY_ENDDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SHOESIZE {
            get {
                return this.sHOESIZEField;
            }
            set {
                this.sHOESIZEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PANTS_CODE {
            get {
                return this.pANTS_CODEField;
            }
            set {
                this.pANTS_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COAT_CODE {
            get {
                return this.cOAT_CODEField;
            }
            set {
                this.cOAT_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NEEDDROM {
            get {
                return this.nEEDDROMField;
            }
            set {
                this.nEEDDROMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DORM_BED {
            get {
                return this.dORM_BEDField;
            }
            set {
                this.dORM_BEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PAY_WAY {
            get {
                return this.pAY_WAYField;
            }
            set {
                this.pAY_WAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SCHEDTYPE {
            get {
                return this.sCHEDTYPEField;
            }
            set {
                this.sCHEDTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATDTYPE {
            get {
                return this.aTDTYPEField;
            }
            set {
                this.aTDTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESIGNTIMES {
            get {
                return this.rESIGNTIMESField;
            }
            set {
                this.rESIGNTIMESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WFBUSYSS {
            get {
                return this.wFBUSYSSField;
            }
            set {
                this.wFBUSYSSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOCLOCK {
            get {
                return this.nOCLOCKField;
            }
            set {
                this.nOCLOCKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PROMOTIONDAY {
            get {
                return this.pROMOTIONDAYField;
            }
            set {
                this.pROMOTIONDAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTRYSOURCR {
            get {
                return this.eNTRYSOURCRField;
            }
            set {
                this.eNTRYSOURCRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECTCODE {
            get {
                return this.rECTCODEField;
            }
            set {
                this.rECTCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECTNAME {
            get {
                return this.rECTNAMEField;
            }
            set {
                this.rECTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOTE {
            get {
                return this.nOTEField;
            }
            set {
                this.nOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATTID {
            get {
                return this.aTTIDField;
            }
            set {
                this.aTTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTID {
            get {
                return this.eNTIDField;
            }
            set {
                this.eNTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDPATH {
            get {
                return this.iDPATHField;
            }
            set {
                this.iDPATHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREATOR {
            get {
                return this.cREATORField;
            }
            set {
                this.cREATORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREATETIME {
            get {
                return this.cREATETIMEField;
            }
            set {
                this.cREATETIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UPDATOR {
            get {
                return this.uPDATORField;
            }
            set {
                this.uPDATORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UPDATETIME {
            get {
                return this.uPDATETIMEField;
            }
            set {
                this.uPDATETIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PROPERTY1 {
            get {
                return this.pROPERTY1Field;
            }
            set {
                this.pROPERTY1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PROPERTY2 {
            get {
                return this.pROPERTY2Field;
            }
            set {
                this.pROPERTY2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PROPERTY3 {
            get {
                return this.pROPERTY3Field;
            }
            set {
                this.pROPERTY3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PROPERTY4 {
            get {
                return this.pROPERTY4Field;
            }
            set {
                this.pROPERTY4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PROPERTY5 {
            get {
                return this.pROPERTY5Field;
            }
            set {
                this.pROPERTY5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INSURANCESTAT {
            get {
                return this.iNSURANCESTATField;
            }
            set {
                this.iNSURANCESTATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADVISERCODE {
            get {
                return this.aDVISERCODEField;
            }
            set {
                this.aDVISERCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADVISERNAME {
            get {
                return this.aDVISERNAMEField;
            }
            set {
                this.aDVISERNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADVISERPHONE {
            get {
                return this.aDVISERPHONEField;
            }
            set {
                this.aDVISERPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JURIDICAL {
            get {
                return this.jURIDICALField;
            }
            set {
                this.jURIDICALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANSORG {
            get {
                return this.tRANSORGField;
            }
            set {
                this.tRANSORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANSEXTIME {
            get {
                return this.tRANSEXTIMEField;
            }
            set {
                this.tRANSEXTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DISPUNIT {
            get {
                return this.dISPUNITField;
            }
            set {
                this.dISPUNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DISPEEXTIME {
            get {
                return this.dISPEEXTIMEField;
            }
            set {
                this.dISPEEXTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KQDATE_START {
            get {
                return this.kQDATE_STARTField;
            }
            set {
                this.kQDATE_STARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KQDATE_END {
            get {
                return this.kQDATE_ENDField;
            }
            set {
                this.kQDATE_ENDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class APPBODY {
        
        private HR_EMPLOYEE_ITEM[] oHR_EMPLOYEE_ITEMField;
        
        private string uSER01Field;
        
        private string uSER02Field;
        
        private string uSER03Field;
        
        private string uSER04Field;
        
        private string uSER05Field;
        
        private string sCHOOLNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OHR_EMPLOYEE_ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public HR_EMPLOYEE_ITEM[] OHR_EMPLOYEE_ITEM {
            get {
                return this.oHR_EMPLOYEE_ITEMField;
            }
            set {
                this.oHR_EMPLOYEE_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER01 {
            get {
                return this.uSER01Field;
            }
            set {
                this.uSER01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER02 {
            get {
                return this.uSER02Field;
            }
            set {
                this.uSER02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER03 {
            get {
                return this.uSER03Field;
            }
            set {
                this.uSER03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER04 {
            get {
                return this.uSER04Field;
            }
            set {
                this.uSER04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER05 {
            get {
                return this.uSER05Field;
            }
            set {
                this.uSER05Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SCHOOLNAME {
            get {
                return this.sCHOOLNAMEField;
            }
            set {
                this.sCHOOLNAMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class APPHDR {
        
        private string uSER01Field;
        
        private string uSER02Field;
        
        private string uSER03Field;
        
        private string uSER04Field;
        
        private string uSER05Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER01 {
            get {
                return this.uSER01Field;
            }
            set {
                this.uSER01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER02 {
            get {
                return this.uSER02Field;
            }
            set {
                this.uSER02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER03 {
            get {
                return this.uSER03Field;
            }
            set {
                this.uSER03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER04 {
            get {
                return this.uSER04Field;
            }
            set {
                this.uSER04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER05 {
            get {
                return this.uSER05Field;
            }
            set {
                this.uSER05Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void SYNEMPLOYEECompletedEventHandler(object sender, SYNEMPLOYEECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SYNEMPLOYEECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SYNEMPLOYEECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SVCBODYS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SVCBODYS)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591