//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WageManagementSystem.EmployeeAttendanceQuery {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087SOAP", Namespace="http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/")]
    public partial class DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087() {
            this.Url = global::WageManagementSystem.Properties.Settings.Default.WageManagementSystem_EmployeeAttendanceQuery_DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087CompletedEventHandler CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/DONLIM_MCASHRM" +
            "S_EMPLOYEEATTENDANCEQUERY_087", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087Response", Namespace="http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/")]
        public DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087Response CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/")] DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_0871 DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087) {
            object[] results = this.Invoke("CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087", new object[] {
                        DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087});
            return ((DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087Response)(results[0]));
        }
        
        /// <remarks/>
        public void CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087Async(DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_0871 DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087) {
            this.CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087Async(DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087, null);
        }
        
        /// <remarks/>
        public void CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087Async(DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_0871 DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087, object userState) {
            if ((this.CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087OperationCompleted == null)) {
                this.CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087OperationCompleted);
            }
            this.InvokeAsync("CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087", new object[] {
                        DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087}, this.CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087OperationCompleted, userState);
        }
        
        private void OnCallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087OperationCompleted(object arg) {
            if ((this.CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087Completed(this, new CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/")]
    public partial class DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_0871 {
        
        private SvcHdrType svcHdrField;
        
        private AppHdrType appHdrField;
        
        private AppBodyType appBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SvcHdrType SvcHdr {
            get {
                return this.svcHdrField;
            }
            set {
                this.svcHdrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppHdrType AppHdr {
            get {
                return this.appHdrField;
            }
            set {
                this.appHdrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppBodyType AppBody {
            get {
                return this.appBodyField;
            }
            set {
                this.appBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/")]
    public partial class SvcHdrType {
        
        private string sOURCEIDField;
        
        private string dESTINATIONIDField;
        
        private string tYPEField;
        
        private string iPADDRESSField;
        
        private string boField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SOURCEID {
            get {
                return this.sOURCEIDField;
            }
            set {
                this.sOURCEIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESTINATIONID {
            get {
                return this.dESTINATIONIDField;
            }
            set {
                this.dESTINATIONIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IPADDRESS {
            get {
                return this.iPADDRESSField;
            }
            set {
                this.iPADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BO {
            get {
                return this.boField;
            }
            set {
                this.boField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/")]
    public partial class QueryResultListTypes {
        
        private string employeeCodeField;
        
        private System.Nullable<double> ycqtsField;
        
        private System.Nullable<double> overTimeField;
        
        private System.Nullable<double> attendanceHourField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EmployeeCode {
            get {
                return this.employeeCodeField;
            }
            set {
                this.employeeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> Ycqts {
            get {
                return this.ycqtsField;
            }
            set {
                this.ycqtsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> OverTime {
            get {
                return this.overTimeField;
            }
            set {
                this.overTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> AttendanceHour {
            get {
                return this.attendanceHourField;
            }
            set {
                this.attendanceHourField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/")]
    public partial class AppBodyTypes {
        
        private string user01Field;
        
        private string user02Field;
        
        private string user03Field;
        
        private string user04Field;
        
        private string user05Field;
        
        private QueryResultListTypes[] queryResultList_ITEMField;
        
        private System.Nullable<int> recordCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User01 {
            get {
                return this.user01Field;
            }
            set {
                this.user01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User02 {
            get {
                return this.user02Field;
            }
            set {
                this.user02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User03 {
            get {
                return this.user03Field;
            }
            set {
                this.user03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User04 {
            get {
                return this.user04Field;
            }
            set {
                this.user04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User05 {
            get {
                return this.user05Field;
            }
            set {
                this.user05Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QueryResultList_ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QueryResultListTypes[] QueryResultList_ITEM {
            get {
                return this.queryResultList_ITEMField;
            }
            set {
                this.queryResultList_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> RecordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/")]
    public partial class AppHdrTypes {
        
        private string user01Field;
        
        private string user02Field;
        
        private string user03Field;
        
        private string user04Field;
        
        private string user05Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User01 {
            get {
                return this.user01Field;
            }
            set {
                this.user01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User02 {
            get {
                return this.user02Field;
            }
            set {
                this.user02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User03 {
            get {
                return this.user03Field;
            }
            set {
                this.user03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User04 {
            get {
                return this.user04Field;
            }
            set {
                this.user04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User05 {
            get {
                return this.user05Field;
            }
            set {
                this.user05Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/")]
    public partial class SvcHdrTypes {
        
        private string rCODEField;
        
        private string rDESCField;
        
        private string eSBCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RCODE {
            get {
                return this.rCODEField;
            }
            set {
                this.rCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RDESC {
            get {
                return this.rDESCField;
            }
            set {
                this.rDESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ESBCODE {
            get {
                return this.eSBCODEField;
            }
            set {
                this.eSBCODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/")]
    public partial class QueryDataType {
        
        private string employeeCodeField;
        
        private System.Nullable<System.DateTime> startTimeField;
        
        private System.Nullable<System.DateTime> endTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EmployeeCode {
            get {
                return this.employeeCodeField;
            }
            set {
                this.employeeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/")]
    public partial class AppBodyType {
        
        private string user01Field;
        
        private string user02Field;
        
        private string user03Field;
        
        private string user04Field;
        
        private string user05Field;
        
        private QueryDataType[] queryData_ITEMField;
        
        private string sourceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User01 {
            get {
                return this.user01Field;
            }
            set {
                this.user01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User02 {
            get {
                return this.user02Field;
            }
            set {
                this.user02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User03 {
            get {
                return this.user03Field;
            }
            set {
                this.user03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User04 {
            get {
                return this.user04Field;
            }
            set {
                this.user04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User05 {
            get {
                return this.user05Field;
            }
            set {
                this.user05Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QueryData_ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public QueryDataType[] QueryData_ITEM {
            get {
                return this.queryData_ITEMField;
            }
            set {
                this.queryData_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/")]
    public partial class AppHdrType {
        
        private string user01Field;
        
        private string user02Field;
        
        private string user03Field;
        
        private string user04Field;
        
        private string user05Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User01 {
            get {
                return this.user01Field;
            }
            set {
                this.user01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User02 {
            get {
                return this.user02Field;
            }
            set {
                this.user02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User03 {
            get {
                return this.user03Field;
            }
            set {
                this.user03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User04 {
            get {
                return this.user04Field;
            }
            set {
                this.user04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User05 {
            get {
                return this.user05Field;
            }
            set {
                this.user05Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.org/DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087/")]
    public partial class DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087Response {
        
        private SvcHdrTypes svcHdrsField;
        
        private AppHdrTypes appHdrsField;
        
        private AppBodyTypes appBodysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SvcHdrTypes SvcHdrs {
            get {
                return this.svcHdrsField;
            }
            set {
                this.svcHdrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppHdrTypes AppHdrs {
            get {
                return this.appHdrsField;
            }
            set {
                this.appHdrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppBodyTypes AppBodys {
            get {
                return this.appBodysField;
            }
            set {
                this.appBodysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087CompletedEventHandler(object sender, CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallDONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DONLIM_MCASHRMS_EMPLOYEEATTENDANCEQUERY_087Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591